name: CI
on:
  #workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - "*"
      - "!**-alpha**"
      
env:
  #CF_API_KEY: ${{ secrets.CF_API_KEY }}
  #WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
  #WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
  GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Create Release Package
        uses: BigWigsMods/packager@master
        with:
          args: -m .pkgmeta
